# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [dev]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/integrated-int222-studart/back-end:dev
      - name: Publish compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./docker-compose.be.yml"
          target: "./back-compose"

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy API Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            touch back-compose/.env
            cd back-compose/
            echo CONECTION=${{ secrets.DB_CONECTION }} >> .env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            echo ALLOWED_CORS=${{ secrets.ALLOWED_CORS }} >> .env
            echo IP_API=${{ secrets.IP_API }} >> .env
            docker-compose -f docker-compose.be.yml pull
            docker-compose -f docker-compose.be.yml up --build -d
